server:
  port: 8082

spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    hikari:
      schema: telegram
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
  flyway:
    enabled: true
    url: ${POSTGRES_DB_URL}
    user: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    schemas: telegram
    baseline-on-migrate: true
    locations: classpath:db/migration
  resources:
    add-mappings: true

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl:
    auto: none

bot:
  name: "GamingPriceBot"
  token: {$BOT_TOKEN:}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
