apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  replicas: 2  # Allow scaling
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service
          image: game-price-bot-backend:latest
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8080
          env:
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: ADMIN_PASSWORD
            - name: IMAGE_FOLDER
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: IMAGE_FOLDER
            - name: KAFKA_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: KAFKA_SERVER_URL
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: POSTGRES_PASSWORD
            - name: FRONT_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: FRONT_SERVICE_URL
            - name: GAME_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: GAME_SERVICE_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: API_KEY
            - name: TOKEN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: TOKEN_SECRET_KEY
            - name: REFRESH_TOKEN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: game-price-bot-secret
                  key: REFRESH_TOKEN_SECRET_KEY
          volumeMounts:
            - name: game-images
              mountPath: "/image_folder"
      volumes:
        - name: game-images
          persistentVolumeClaim:
            claimName: game-images-pvc
