version: "3.9"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - gpb-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka:9093,OUTSIDE://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_LISTENERS: "INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INSIDE"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "gpb_email_event:1:1,gpb_game_name_search_request:1:1,gpb_game_url_search_request:1:1,gpb_game_follow:1:1,gpb_game_unfollow:1:1"
    networks:
      - gpb-network

  react:
    image: ghcr.io/illusiveman2186/game-price-bot-react:latest
    build:
      context: ./gpb-front
    container_name: gpb_front_react
    networks:
      - gpb-network
    ports:
      - "3000:80"
    environment:
      BACKEND_SERVICE_URL: ${BACKEND_SERVICE_URL}
      TELEGRAM_BOT_URL: ${TELEGRAM_BOT_URL}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - gpb-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  game:
    image: ghcr.io/illusiveman2186/game-price-bot-game:latest
    container_name: gpb_game
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    build:
      context: ./gpb-game
      args:
        DEPENDENCY_REPO_URL: ${DEPENDENCY_REPO_URL}
        DEPENDENCY_REPO_USERNAME: ${DEPENDENCY_REPO_USERNAME}
        DEPENDENCY_REPO_PASSWORD: ${DEPENDENCY_REPO_PASSWORD}
    networks:
      - gpb-network
    environment:
      - IMAGE_FOLDER=${IMAGE_FOLDER}
      - KAFKA_SERVER_URL=${KAFKA_SERVER_URL}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - API_KEY=${API_KEY}
    volumes:
      - common_data_images:${IMAGE_FOLDER}

  backend:
    image: ghcr.io/illusiveman2186/game-price-bot-backend:latest
    container_name: gpb_backend
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres
      - game
    networks:
      - gpb-network
    build:
      context: ./gpb-backend
      args:
        DEPENDENCY_REPO_URL: ${DEPENDENCY_REPO_URL}
        DEPENDENCY_REPO_USERNAME: ${DEPENDENCY_REPO_USERNAME}
        DEPENDENCY_REPO_PASSWORD: ${DEPENDENCY_REPO_PASSWORD}
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - IMAGE_FOLDER=${IMAGE_FOLDER}
      - KAFKA_SERVER_URL=${KAFKA_SERVER_URL}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - FRONT_SERVICE_URL=${FRONT_SERVICE_URL}
      - GAME_SERVICE_URL=${GAME_SERVICE_URL}
      - API_KEY=${API_KEY}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - REFRESH_TOKEN_SECRET_KEY=${REFRESH_TOKEN_SECRET_KEY}
    volumes:
      - common_data_images:${IMAGE_FOLDER}

  telegram:
    image: ghcr.io/illusiveman2186/game-price-bot-telegram:latest
    container_name: gpb_telegram
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - postgres
    networks:
      - gpb-network
    build:
      context: ./gpb-telegram
      args:
        DEPENDENCY_REPO_URL: ${DEPENDENCY_REPO_URL}
        DEPENDENCY_REPO_USERNAME: ${DEPENDENCY_REPO_USERNAME}
        DEPENDENCY_REPO_PASSWORD: ${DEPENDENCY_REPO_PASSWORD}
    environment:
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - IMAGE_FOLDER=${IMAGE_FOLDER}
      - KAFKA_SERVER_URL=${KAFKA_SERVER_URL}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GAME_SERVICE_URL=${GAME_SERVICE_URL}
      - API_KEY=${API_KEY}
      - FRONT_SERVICE_URL=${FRONT_SERVICE_URL}
    volumes:
      - common_data_images:${IMAGE_FOLDER}

  email:
    image: ghcr.io/illusiveman2186/game-price-bot-email:latest
    container_name: gpb_email
    depends_on:
      - kafka
    build:
      context: ./gpb-email
      args:
        DEPENDENCY_REPO_URL: ${DEPENDENCY_REPO_URL}
        DEPENDENCY_REPO_USERNAME: ${DEPENDENCY_REPO_USERNAME}
        DEPENDENCY_REPO_PASSWORD: ${DEPENDENCY_REPO_PASSWORD}
    networks:
      - gpb-network
    environment:
      - KAFKA_SERVER_URL=${KAFKA_SERVER_URL}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}

volumes:
  common_data_images:
  postgres_data:


networks:
  gpb-network:
    driver: bridge
