apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: inside
      port: 9093
      targetPort: 9093
    - name: outside
      port: 9092
      targetPort: 9092
  type: ClusterIP
