apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: game-price-bot-tls
  namespace: game-price-bot
spec:
  secretName: game-price-bot-tls
  dnsNames:
    - game.price.bot
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
