apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-service
spec:
  selector:
    app: telegram-bot
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP  # Internal access only
