name: Build, Test & Check Coverage

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  # 🛠 Build & Test Gradle-Based Services (gpb-backend, gpb-email, gpb-game)
  build-and-test-gradle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [gpb-backend, gpb-email, gpb-game]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build ${{ matrix.service }} (with Dependency Repo)
        run: |
          cd ${{ matrix.service }}
          gradle clean build -x test \
            -PDEPENDENCY_REPO_URL=${{ secrets.DEPENDENCY_REPO_URL }} \
            -PDEPENDENCY_REPO_USERNAME=${{ secrets.DEPENDENCY_REPO_USERNAME }} \
            -PDEPENDENCY_REPO_PASSWORD=${{ secrets.DEPENDENCY_REPO_PASSWORD }}

      - name: Run Unit Tests & Enforce Coverage (No Report)
        run: |
          cd ${{ matrix.service }}
          gradle test jacocoTestCoverageVerification

  # 🔹 Build & Test Maven-Based Service (gpb-telegram)
  build-and-test-maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: 3.8.6

      - name: Build gpb-telegram (with Dependency Repo)
        run: |
          cd gpb-telegram
          mvn clean package -DskipTests \
            -Drepo.url=${{ secrets.DEPENDENCY_REPO_URL }} \
            -Drepo.username=${{ secrets.DEPENDENCY_REPO_USERNAME }} \
            -Drepo.password=${{ secrets.DEPENDENCY_REPO_PASSWORD }}

      - name: Run Unit Tests & Enforce Coverage (No Report)
        run: |
          cd gpb-telegram
          mvn test jacoco:check

# 🚀 Frontend Service (No Docker, Direct npm Build)
  build-gpb-front:
    runs-on: ubuntu-latest
    needs: [build-and-test-gradle, build-and-test-maven]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies & Build React
        run: |
          cd gpb-front
          npm install
          npm run build
  
